### PR TITLE
Added Documentation for Metadata disk size limitation.

### PR DESCRIPTION
**Pull request by JugalPatil**
Due to bug CORTX-29365 Metadata disk size cannot exceed 20TB.
This bug was introduced after migration to Rocky Linux 8.4 and was not present in Centos 7.9.
There are no limitations on data disk size.

Signed-off-by: Jugal Patil <jugal.patil@seagate.com>

### CODE REVIEW

**Review by osowski — APPROVED** [review]
lgtm

**Comment by osowski** [comment]
Just noticed this was targeted at `main` and it should be targeted against `integration` instead. Switching that now and letting GitHub do its thing. Will take a look once it's updated.

**Review by osowski — CHANGES_REQUESTED** [review]
@JugalPatil  Can you update your remote integration branch based upon what is here and submit the PR from your remote branch to the current integration branch?

Per our CONTRIBUTING.md, PRs should be made against `integration` and not `main`.

**Comment by JugalPatil** [comment]
Hi @osowski thanks for the input. I have rebased my remote branch with latest integration branch. Hope that works.

**Review by osowski — APPROVED** [review]

**Pull request merged**
