### PR TITLE
convert conflucence doc to MD (#123)

### LINKED ISSUE #123: Convert confluence doc into markdown
At this location (https://github.com/Seagate/cortx-k8s#using-cortx-on-kubernetes), there is a TODO item which looks like:

Using CORTX on Kubernetes
TODO Port https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/754155622/CORTX+Kubernetes+N-Pod+Deployment+and+Upgrade+Document+using+Services+Framework#5.-Understanding-Management-and-S3-Endpoints-and-configuring-External-Load-balancer-service(Optional) here or into a linked doc/readme file. 

This action needs to be done and the PR doing it needs to refer back to this Issue.

### PR DESCRIPTION
**Pull request by anubhav06**
Ref: #123 

- Converted the CORTEX Endpoints docs in Markdown
- Updated README by linking to the new docs created

-----
[View rendered README.md](https://github.com/anubhav06/cortx-k8s/blob/issue-#123/README.md)
[View rendered doc/cortx-on-k8s.md](https://github.com/anubhav06/cortx-k8s/blob/issue-#123/doc/cortx-on-k8s.md)

### CODE REVIEW

**Comment by johnbent** [comment]
This PR does not need CLA-signed so that check can be ignored.

**Comment by johnbent** [comment]
@osowski , when this PR is resolved, can you please add one of the following tags in a comment to this PR:
■ #SODACODE-PR-Accepted
■ #SODACODE-PR-Rejected
Thanks!

**Comment by anubhav06** [comment]
> Thank you for the contribution! We are actively working on this page for an impending release, so I will circle back on reviewing this PR tomorrow (3/4). There will more than likely need to be a rebase for your changes here, based on multiple updates to the other areas of README.md for our release work.

Does this mean that I have to rebase the branch ? Sorry for asking as I'm new to open source contributions,

**Comment by osowski** [comment]
@anubhav06 Thank you for digging in here! At the moment, it does not mean you need to rebase your work, as there is another work item progressing that will work on the same section - contributing an entire net-new set of steps due to an internal component rip-and-replace workstream that was done in a recent release. Once that work item is completed based upon the new component's workflow, I will circle back here and see what is still applicable for the initial source document this issue was asking to port to markdown.

For now, there is nothing you need to do.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
