### PR TITLE
CORTX-29435: Fix contact links (issue forms)

### PR DESCRIPTION
**Pull request by keithpine**
Signed-off-by: Keith Pine <keith.pine@seagate.com>

## Description
Fix the issue template contact links. Some missing fields appear to make them not render.

Add new links pointing to the main CORTX project for feature requests, Discussions for cortx-k8s support, and Slack for general CORTX community support.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds new functionality)
- [ ] Third-party dependency update
- [X] Documentation additions or improvements
- [ ] Code quality improvements to existing code or test additions/updates
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)

## Applicable issues
- This change is related to an issue: CORTX-29435

## How was this tested?
Using my fork repo.

image

## Checklist

- [ ] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [X] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change addresses a CORTX Jira issue:

- [X] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

### CODE REVIEW

**Comment by keithpine** [comment]
The only thing missing in that screenshot is the link to the Security policy for security vulnerability reports. I'm assuming that's just because my fork doesn't have a policy, whereas the Seagate organization does, so it _should_ also show up once this is merged (won't know until then).

**Review by walterlopatka — APPROVED** [review]
lgtm

**Comment by keithpine** [comment]
> After talking with @gregnsk and @johnbent , we should have the following links:
> 
>     * `Feature requests` should point to https://github.com/Seagate/cortx/issues/new
> 
>     * `Community Support` should point to Slack via https://cortx.link/slack_invite

Sure, I'll point to this links. But I have to say, the CORTX new issue could sure use a template itself. It currently just goes to a blank new issue page which isn't great. Preferably it would go to a Feature Request template/form.

**Comment by osowski** [comment]
Agreed. We can open a (very meta) issue on the main repo to get some of that streamlined and that should help the community team.

**Comment by johnbent** [comment]
> Agreed. We can open a (very meta) issue on the main repo to get some of that streamlined and that should help the community team.

Thanks @keithpine and @osowski , I created an Issue so that the parent can get those templates as well:
https://github.com/Seagate/cortx/issues/1477

**Review by johnbent — APPROVED** [review]
lgtm

**Review by osowski — APPROVED** [review]
lgtm

**Pull request merged**
