### PR TITLE
CORTX-29723: remove mocking from cortx-client-pod init container

### PR DESCRIPTION
**Pull request by tanujashinde0405**
Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

### CODE REVIEW

**Comment by keithpine** [comment]
I tried this and the client pods don't finish the Init phase. Looks like hare_setup is hung.

```
h-4.4# ps -efjH | more
UID         PID   PPID   PGID    SID  C STIME TTY          TIME CMD
root        120      0    120    120  0 17:25 pts/0    00:00:00 sh
root        128    120    128    120  0 17:25 pts/0    00:00:00   ps -efjH
root        129    120    128    120  0 17:25 pts/0    00:00:00   more
root          1      0      1      1  0 15:08 ?        00:00:00 /bin/bash /opt/seagate/cortx/provisioner/bin/cortx_deploy -n f3be4345743444fab1e7abec7537de1a -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf
root         62      1      1      1  0 15:08 ?        00:00:00   /usr/libexec/platform-python /usr/bin/cortx_setup cluster bootstrap -c yaml:///etc/cortx/cluster.conf
root         89     62      1      1  0 15:08 ?        00:00:00     /usr/bin/python3.6 /opt/seagate/cortx/hare/bin/hare_setup prepare --config yaml:///etc/cortx/cluster.conf --services all
root         91     89      1      1  1 15:08 ?        00:01:30       consul agent -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -data-dir=/etc/cortx/hare/config//f3be4345743444fab1e7abec7537de1a/consul/data -enable-script-checks -conf
ig-dir=/etc/cortx/hare/config//f3be4345743444fab1e7abec7537de1a/consul/config -domain=consul -serf-lan-port=8301 -retry-join=consul-server.default.svc.cluster.local:8301
```

**Comment by keithpine** [comment]
I checked the hare logs and it shows:

```
2022-03-29 15:08:58,002 [ERROR] Required key 'node>f3be4345743444fab1e7abec7537de1a>storage>cvg' not found at URL: yaml:///etc/cortx/cluster.conf
```

It seems hare does not support this yet?

**Review by tanujashinde0405 — COMMENTED** [review]
@madhavemuri  @SwapnilGaonkar7 @atulsdeshmukh2312, Please refer to above Keith's comment. After removing mock from client pod, hare is getting stuck in init phase.

**Comment by madhavemuri** [comment]
> @madhavemuri @SwapnilGaonkar7 @atulsdeshmukh2312, Please refer to above Keith's comment. After removing mock from client pod, hare is getting stuck in init phase.

Following PR's too needs to merged in main along with this change,
https://github.com/Seagate/cortx-motr/pull/1566/files [Motr PR]
https://github.com/Seagate/cortx-hare/pull/2037  [Hare PR]

**Comment by madhavemuri** [comment]
@tanujashinde0405 : https://github.com/tanujashinde0405/cortx-k8s/ -b rgw_s3-change is needed for rgw-s3 services related change, due to which merging for hare PR is blocked.
cc @supriyachavan4398 @atulsdeshmukh2312

**Review by tanujashinde0405 — COMMENTED** [review]
@keithpine , we need to merge : https://github.com/Seagate/cortx-hare/pull/2037 and this current PR together. Can we approve this PR and setup one call to merge this PR's together?

**Comment by osowski** [comment]
> @keithpine , we need to merge : [Seagate/cortx-hare#2037](https://github.com/Seagate/cortx-hare/pull/2037) and this current PR together. Can we approve this PR and setup one call to merge this PR's together?

We need to be moving away from developing such that "these PRs [in different repos] need to be merged together". If we need to have a larger discussion about what that looks like in the codebase to support more adaptive coding and interaction between components, I am happy to facilitate.

**Review by tanujashinde0405 — COMMENTED** [review]
@osowski @keithpine, We have merged the dependent hare PR: https://github.com/Seagate/cortx-hare/pull/2037, Are we good to merge this PR now?

**Review by keithpine — APPROVED** [review]

**Comment by osowski** [comment]
> @osowski @keithpine, We have merged the dependent hare PR: [Seagate/cortx-hare#2037](https://github.com/Seagate/cortx-hare/pull/2037), Are we good to merge this PR now?

This looks good to me. Is there a specific cortx-all container image version we should be using to verify availability? The earliest image version I can see the referenced PR being available in is [cortx-all:2.0.0-724](https://github.com/Seagate/cortx/pkgs/container/cortx-all/19008956?tag=2.0.0-724).

**Comment by keithpine** [comment]
I personally used 725, which is the current version (also 0.3.0) set in solution.example.yaml.

**Pull request merged**
