### PR TITLE
CORTX-32010: improve deployment wait and timeout handling

### PR DESCRIPTION
**Pull request by keithpine**
## Description

Change how Charts are installed and resources waited for.

### CORTX Chart install

The `--wait` argument has been removed from the `helm install` command. Previously, if this Chart failed to install within the default wait timeout (5 minutes), then the deployment script would exit. This leaves the cluster in a half-installed state, requiring an un-deploy and retry. In addition, we shouldn't assume the default timeout is reasonable in all configurations. Instead, just install without waiting and either check for the resource availability later, and/or let the user determine the completion status.

### Data / Server / Client Chart installs

Similar to the above, instead of installing these serially (install then wait), they are now installed in parallel without waiting. Based on testing, there doesn't appear to be any dependency on these deployments. This reduces the total wait time of the deployment, and again let's the user decide whether they want to wait or not. This also introduces the same behavior that we'll expect to see when these Charts are merged into the Unified chart.

### Restore lost Control and HA waits

After the Control and HA Charts were merged into the unified Chart, the ability to wait on these resources was lost, making `CORTX_DEPLOY_CONTROL_TIMEOUT` and `CORTX_DEPLOY_HA_TIMEOUT` in-effective. This code was restored and these deployments are waited on again.

Also added an additional `CORTX_DEPLOY_CLIENT_TIMEOUT` variable for Client deployments.

### Wait method

The script was using `kubectl wait` to wait on the Deployments. This command _only_ works for some resources, like Deployments and Pods, that have a working `status` metadata field. It does not work for StatefulSets. Since we are moving to StatefulSets for some resources (Data and Server), it makes sense to now also move to `kubectl rollout status` which works for both Deployment and StatefulSet resource types.

### Parallel waits

Since the Chart installs are no longer serialized, the waits are also now done in parallel. This preserves the expected wait timeout values. Otherwise, if the waits were serialized the times would be additive.

The waits are also moved to the end of the script, after everything is installed. This means users have the option of canceling the wait (Ctrl-C) and exiting early, without it resulting in a partially installed cluster.

## Breaking Change

The waits used to execute the kubectl wait command twice for each deployment, which means the actual timeout could be 2x the specified time. This double wait has been removed, so the actual timeouts are closer to the specified values. If you are using custom timeouts (via environment variable), those will need to be doubled to have the same behavior as before.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds new functionality)
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)
- [ ] Third-party dependency update
- [ ] Documentation additions or improvements
- [ ] Code quality improvements to existing code or test additions/updates

## How was this tested?

Deployed a cluster and performed S3 I/O.

Set a timeout low for a deployment and observed it was reported as an error. Checked cluster after and it was working, as expected.

Used Ctrl-C to stop the waits. `kubectl rollout status` background processes were killed successfully, and cluster continued to install successfully after a time.

## Additional information

Fixed an issue where a non-fatal error message would be reported during a data-only deployment, as the code to build the Chart value file was incorrectly attempting to read non-existent HA and Control machine ID files.

Due to that mishap, improved how "data-only" deployments are handled. Now we use a flag for each component, vs. checking the deployment type everywhere.

Removed the `...` printing during the waits. Since these are done in parallel, including this makes the output hard to read. The `rollout status` provides some iterative output as Pods become ready, so not all progress indication is lost.

Examples of the new timeout behavior (click arrows to expand):

<details>
<summary>A successful deployment</summary>

```text
-----------------------------------------------------------

** Please wait while CORTX Kubernetes resources are being deployed. **

The S3 data service is accessible through the cortx-io-svc-0 service.
   Default IAM access key: sgiamadmin
   Default IAM secret key is accessible via:
      kubectl get secrets/cortx-secret --namespace cortx \
        --template={{.data.s3_auth_admin_secret}} | base64 -d

The CORTX control service is accessible through the cortx-control-loadbal-svc service.
   Default control username: cortxadmin
   Default control password is accessible via:
      kubectl get secrets/cortx-secret --namespace cortx \
        --template={{.data.csm_mgmt_admin_secret}} | base64 -d

-----------------------------------------------------------

Now waiting for all CORTX resources to become available, press Ctrl-C to quit...

Waiting for deployment "cortx-server-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-server-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-ha" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-control" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
deployment "cortx-ha" successfully rolled out
Rollout of deployment/cortx-ha finished after 21 seconds
deployment "cortx-control" successfully rolled out
Rollout of deployment/cortx-control finished after 44 seconds
deployment "cortx-client-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-client-ssc-vm-g3-rhev4-2988 finished after 67 seconds
deployment "cortx-client-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-client-ssc-vm-g3-rhev4-2986 finished after 72 seconds
deployment "cortx-data-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-data-ssc-vm-g3-rhev4-2988 finished after 96 seconds
deployment "cortx-data-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-data-ssc-vm-g3-rhev4-2986 finished after 99 seconds
deployment "cortx-server-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-server-ssc-vm-g3-rhev4-2988 finished after 136 seconds
deployment "cortx-server-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-server-ssc-vm-g3-rhev4-2986 finished after 136 seconds

The CORTX cluster installation is complete.
```

</details>

<details>
<summary>A deployment with timeouts</summary>

In this case, the cortx-server deployments timed out after a shortened 5 second timeout. (The cluster eventually comes up).

```text
-----------------------------------------------------------

** Please wait while CORTX Kubernetes resources are being deployed. **

The S3 data service is accessible through the cortx-io-svc-0 service.
   Default IAM access key: sgiamadmin
   Default IAM secret key is accessible via:
      kubectl get secrets/cortx-secret --namespace cortx \
        --template={{.data.s3_auth_admin_secret}} | base64 -d

The CORTX control service is accessible through the cortx-control-loadbal-svc service.
   Default control username: cortxadmin
   Default control password is accessible via:
      kubectl get secrets/cortx-secret --namespace cortx \
        --template={{.data.csm_mgmt_admin_secret}} | base64 -d

-----------------------------------------------------------

Now waiting for all CORTX resources to become available, press Ctrl-C to quit...

Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-control" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-server-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
deployment "cortx-ha" successfully rolled out
Waiting for deployment "cortx-server-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Rollout of deployment/cortx-ha finished after 0 seconds
deployment "cortx-control" successfully rolled out
Rollout of deployment/cortx-control finished after 4 seconds
error: timed out waiting for the condition
ERROR: Rollout of deployment/cortx-server-ssc-vm-g3-rhev4-2986 timed out after 5 seconds
error: timed out waiting for the condition
ERROR: Rollout of deployment/cortx-server-ssc-vm-g3-rhev4-2988 timed out after 5 seconds
deployment "cortx-client-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-client-ssc-vm-g3-rhev4-2986 finished after 69 seconds
deployment "cortx-client-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-client-ssc-vm-g3-rhev4-2988 finished after 72 seconds
deployment "cortx-data-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-data-ssc-vm-g3-rhev4-2988 finished after 92 seconds
deployment "cortx-data-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-data-ssc-vm-g3-rhev4-2986 finished after 93 seconds

ERROR: A timeout occurred while waiting for one or more resources during the CORTX cluster installation.
```
</details>

<details>
<summary>A deployment that was canceled with Ctrl-C during the wait time</summary>

```text
-----------------------------------------------------------

Now waiting for all CORTX resources to become available, press Ctrl-C to quit...

Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-control" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-server-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-server-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-ha" rollout to finish: 0 of 1 updated replicas are available...
deployment "cortx-ha" successfully rolled out
Rollout of deployment/cortx-ha finished after 10 seconds
deployment "cortx-control" successfully rolled out
Rollout of deployment/cortx-control finished after 22 seconds
^C
Ctrl-C was detected, quitting now...
$ pgrep kubectl

$
```
</details>

<details>
<summary>A successful data-only deployment</summary>

```text
-----------------------------------------------------------

** Please wait while CORTX Kubernetes resources are being deployed. **

-----------------------------------------------------------

Now waiting for all CORTX resources to become available, press Ctrl-C to quit...

Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-client-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2986" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "cortx-data-ssc-vm-g3-rhev4-2988" rollout to finish: 0 of 1 updated replicas are available...
deployment "cortx-client-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-client-ssc-vm-g3-rhev4-2986 finished after 54 seconds
deployment "cortx-client-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-client-ssc-vm-g3-rhev4-2988 finished after 55 seconds
deployment "cortx-data-ssc-vm-g3-rhev4-2988" successfully rolled out
Rollout of deployment/cortx-data-ssc-vm-g3-rhev4-2988 finished after 83 seconds
deployment "cortx-data-ssc-vm-g3-rhev4-2986" successfully rolled out
Rollout of deployment/cortx-data-ssc-vm-g3-rhev4-2986 finished after 84 seconds

The CORTX cluster installation is complete.
```
</details>

### Related issues

Note that there are existing issues logged for initContainers never completing:

- HA deployment: CORTX-31665
- Control deployment: CORTX-31536

With this change, the script will install everything and report these deployments as having timed out. While these services are indeed unavailable, in my usage I can still do S3 I/O with the default user, as long as Data and Server startup correctly. So the benefit here is that a somewhat working deployment, instead of a half-installed cluster. As a workaround, you can just delete the Control/HA Pods, and they will be created successfully.

## Checklist

- [X] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [X] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change addresses a CORTX Jira issue:

- [X] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/optimize-wait/README.md)

-----
[View rendered README.md](https://github.com/keithpine/cortx-k8s/blob/CORTX-32010_optimize-wait/README.md)

### CODE REVIEW

**Review by walterlopatka — APPROVED** [review]
lgtm

**Comment by keithpine** [comment]
I doubled the default timeout values to match the originals. The originals were basically 2x the number specified. I think it makes sense to be more conservative so there are no surprises.

**Comment by keithpine** [comment]
I've observed that if the rgw server comes up a little before the data pods, there will be a 10 minute hang. According to the logs, it is attempting to create the rgw admin user. Seems there's an issue in the retry logic there, after 10 minutes it will retry and succeed. What's it doing during those 10 minutes, when the data pods have been ready? Again, as with HA and Control pods, killing the offending Pod will get everything going again.

**Review by osowski — APPROVED** [review]
lgtm

**Pull request merged**
