### PR TITLE
Update tested by section

### PR DESCRIPTION
**Pull request by hessio**
Adding my name to the tested by section

Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds new functionality)
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)
- [ ] Third-party dependency update
- [x] Documentation additions or improvements
- [x] Code quality improvements to existing code or test additions/updates

## Applicable issues

- This change fixes an issue: #
- This change is related to an issue: #

## CORTX image version requirements

This change requires the following images:

- `cortx-data:<version>`
- `cortx-rgw:<version>`
- `cortx-control:<version>`

## Checklist

- [x] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [x] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change requires newer CORTX or third party image versions:

- [ ] The `image` fields in [solution.example.yaml](../k8_cortx_cloud/solution.example.yaml) have been updated to use the required versions.
- [ ] The `appVersion` field of the [Helm chart](../charts/cortx/Chart.yaml) has been updated to use the new CORTX version.

If this change addresses a CORTX Jira issue:

- [ ] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

-----
[View rendered doc/cortx-minikube-k8s-installation.md](https://github.com/Seagate/cortx-k8s/blob/hessio-patch-1/doc/cortx-minikube-k8s-installation.md)

### CODE REVIEW

**Comment by walterlopatka** [comment]
@hessio , looks good, but please add a comment in the PR description saying what you are doing.  (I know it's pretty clear, but we want to have consistency in our PR submissions, especially as members of other teams contribute more.)

**Comment by hessio** [comment]
@walterlopatka can you please review this PR?

**Comment by keithpine** [comment]
Seems like the instructions should also be updated along with these "tested by" updates?

Still shows using an older version.

```
git clone -b v0.0.22 https://github.com/Seagate/cortx-k8s
cd cortx-k8s/k8_cortx_cloud/
```

**Review by walterlopatka — APPROVED** [review]

**Review by keithpine — CHANGES_REQUESTED** [review]
When testing with a new version, please update the documentation to reflect the necessary steps needed for that version. This will help us keep the document maintained. Thanks.

**Comment by hessio** [comment]
Oh I see - I think I used this branch of k8s repo so then I didn't use the most up to date version @keithpine ?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
