### PR TITLE
CORTX-31012:  Include timestamp in Core dump filename.

### PR DESCRIPTION
**Pull request by papan-singh**
Signed-off-by: Papan Kumar Singh <papan.kumarsingh@seagate.com>

## Description

To avoid same core file name when m0d start with the same pid,
add timestamp in core file name.
Currently core file name is core.<pid>,
Change it to core.<timestamp>.<pid>
## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds new functionality)
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)
- [ ] Third-party dependency update
- [ ] Documentation additions or improvements
- [ ] Code quality improvements to existing code or test additions/updates

## Applicable issues

- This change fixes an issue: #CORTX-31012
- This change is related to an issue: #

## CORTX image version requirements

This change requires the following images:

- `cortx-all:<version>`
- `cortx-rgw:<version>`

## How was this tested?
[root@cortx-data-headless-svc-ssc-vm-rhev4-2614 ~]# sysctl -a | grep core
kernel.core_pattern = core.%t

[root@cortx-data-headless-svc-ssc-vm-rhev4-2614 m0d-0x7200000000000001:0x5a]# pwd
/etc/cortx/motr/m0d-0x7200000000000001:0x5a
[root@cortx-data-headless-svc-ssc-vm-rhev4-2614 m0d-0x7200000000000001:0x5a]# ls
core.1651139893.104  db  db-log  stobs

## Checklist

- [x] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [x] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change addresses a CORTX Jira issue:

- [x] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

### CODE REVIEW

**Comment by walterlopatka** [comment]
@papan-singh, I know this is a simple change,  but please fill out the info in the PR template as requested.

**Review by walterlopatka — APPROVED** [review]
lgtm

**Comment by papan-singh** [comment]
> The change as-is looks good, but it should also be made in `k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-cm-nodeconfig.yaml` as well.
> 
> The prereq script is only a recommended reference approach to what a cluster is needed to have to run and is not required by the end user to be run. The nodeconfig script is included at startup time for each of the Data Pods and while redundant at the moment, is more likely the long-term landing place for anything in the prereq script that we will persist long-term.

incorporated

**Review by osowski — APPROVED** [review]
lgtm

**Pull request merged**
