### PR TITLE
CORTX-33534: Exit on errors in logs-cortx-cloud.sh

### PR DESCRIPTION
**Pull request by walterlopatka**
## Description
Improve error handling in logs-cortx-cloud.sh by exiting on any failure, either in the background log collection processes or the final tar.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds new functionality)
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)
- [ ] Third-party dependency update
- [ ] Documentation additions or improvements
- [ ] Code quality improvements to existing code or test additions/updates

## Applicable issues

- This change fixes an issue: CORTX-33534
- This change is related to an issue: #

## CORTX image version requirements
NA

## How was this tested?
Tested locally:
* Failure in background process (executable not in path)
* Failure in final tar (executable not in path)
* Confirmed error code fails

## Checklist

- [x] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [x] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change requires newer CORTX or third party image versions:

- [ ] The `image` fields in [solution.example.yaml](../k8_cortx_cloud/solution.example.yaml) have been updated to use the required versions.
- [ ] The `appVersion` field of the [Helm chart](../charts/cortx/Chart.yaml) has been updated to use the new CORTX version.

If this change addresses a CORTX Jira issue:

- [x] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

### CODE REVIEW

**Comment by keithpine** [comment]
I don't think I understand the original issue and what's being solved. If one command fails for all Pods/Containers, does that mean the entire process is aborted? If so, wouldn't it be better to collect as much information as is available, and report that some things failed?

**Comment by walterlopatka** [comment]
> I don't think I understand the original issue and what's being solved. If one command fails for all Pods/Containers, does that mean the entire process is aborted? If so, wouldn't it be better to collect as much information as is available, and report that some things failed?

Hmmmmm..... you make a very good point!  Let me reconsider this.

**Comment by walterlopatka** [comment]
FYI, I am delayed in returning to this PR.  I will get back to it in the next week or two.

**Comment by rahul-tripathi-git** [comment]
> I don't think I understand the original issue and what's being solved. If one command fails for all Pods/Containers, does that mean the entire process is aborted? If so, wouldn't it be better to collect as much information as is available, and report that some things failed?

Yes this sounds perfect, also please consider having a log file (for every bundle generation) where such error can be reported and refered by end user.

CC: @cdeshmukh

**Comment by walterlopatka** [comment]
Closed in favor of #367

**Pull request closed without merging**
