### PR TITLE
CORTX-29822: Remove items deprecated in v0.2.0

### PR DESCRIPTION
**Pull request by keithpine**
Release v0.2.0 deprecated some things, to be removed for v0.3.0. This change removes them.

- solution.yaml file -> solution.example.yaml replaces it
- Default passwords -> default is now random ones
- Update `logs-cortx-cloud.sh` to properly abort if the `solution.yaml` file is not found

Testing:

- Deployed cluster w/o passwords, did I/O with random created password
- Executed `*.sh` scripts. They abort with `ERROR: solution.yaml does not exist` or similar, as expected.

### CODE REVIEW

**Comment by keithpine** [comment]
@shailesh-vaidya do you need any time to update CI processes in regards to this change?

**Review by walterlopatka — CHANGES_REQUESTED** [review]
Also remove the passwords from solution_stub.yaml

**Review by walterlopatka — APPROVED** [review]
lgtm 🐬

**Comment by shailesh-vaidya** [comment]
@keithpine Let me test deployment from your fork i.e. https://github.com/keithpine/cortx-k8s/tree/CORTX-29822_remove-deprecated and will update. 
Could you please let me know how to fetch dynamically generated passwords after this change. We fetch them for testing IO operation.

**Comment by shailesh-vaidya** [comment]
> @keithpine Let me test deployment from your fork i.e. https://github.com/keithpine/cortx-k8s/tree/CORTX-29822_remove-deprecated and will update. Could you please let me know how to fetch dynamically generated passwords after this change. We fetch them for testing IO operation.

@keithpine  CORTX deployment is failing in `./prereq-deploy-cortx-cloud.sh` execution. Error is as below,

```
[root@ssc-vm-g4-rhev4-1297 k8_cortx_cloud]# ./prereq-deploy-cortx-cloud.sh -d /dev/sdb
ERROR: solution.yaml does not exist
```
Seems we need change at - https://github.com/keithpine/cortx-k8s/blob/CORTX-29822_remove-deprecated/k8_cortx_cloud/prereq-deploy-cortx-cloud.sh#L9

**Comment by shailesh-vaidya** [comment]
> > CORTX deployment is failing in ./prereq-deploy-cortx-cloud.sh execution. Error is as below
> 
> @shailesh-vaidya You'll have to say more, because that looks like it's working as intended? Since `solution.yaml` has been removed, you need to provide it yourself in one way or another. You have multiple options.
> 
> 1. Copy your solution file to `solution.yaml`, which is the default filename used by all scripts.
>    ```
>    $ cp my_solution.yaml solution.yaml
>    $ ./prereq-deploy-cortx-cloud.sh -d /dev/sdb
>    ```
> 2. Specify the solution file using the command line argument.
>    ```
>    $ ./prereq-deploy-cortx-cloud.sh -d /dev/sdb -s my_solution.yaml
>    ```
> 3. Use the environment variable `CORTX_SOLUTION_CONFIG_FILE`.
>    ```
>    $ export CORTX_SOLUTION_CONFIG_FILE=my_solution.yaml
>    $ ./prereq-deploy-cortx-cloud.sh -d /dev/sdb
>    ```
> 
> For your purposes, I would recommend option 1. Just copy your solution file to `solution.yaml` prior to deploying, and it will be the same as before. We still provide `solution.example.yaml`, if that's what you want to base your deployment on, just copy that file then.
> 
> I think _most_ of the scripts support the `-s <solution_file>` command arg, but I'm not sure _all_ of them do. I know for a fact that not all scripts support the environment variable, so I'd avoid that for now. A TODO for me is to unify all the scripts to support the same command line args and environment variable.

Thanks for the details. Let me copy solution.yaml before executing `./prereq-deploy-cortx-cloud.sh` and it should work. I will check and confirm on this. 

> 
> > Could you please let me know how to fetch dynamically generated passwords after this change. We fetch them for testing IO operation.
> 
> You don't have to rely on the random passwords, if you're already editing the solution file you can just set the passwords to any known ones you want.
> 
> If you do want to fetch them, you can get the passwords from the secret and b64 decode them. At the end of the deploy script it prints the exact commands to get the CSM and S3 passwords, but in general you can using this construct:
> 
> ```
> $ kubectl get secrets/<cortx_secret_name> --template={{.data.<password_name>}} | base64 -d
> ```
> 
> Replace `<cortx_secret_name>` with your configured name (default is `cortx-secret`) and `<password_name>` with the name of password key you want, e.g. `s3_auth_admin_secret` for the root S3 user's secret key. This prints the S3 secret key:
> 
> ```
> $ kubectl get secrets/cortx-secret --template={{.data.s3_auth_admin_secret}} | base64 -d
> y3rZj%LMqE@N$m3!
> ```

Thanks for this. I will use `kubectl get secrets/cortx-secret` instead of getting them from solution.yaml.

**Comment by keithpine** [comment]
@shailesh-vaidya Looks like you've made a change to support this. Is this good to merge now?

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya Looks like you've made a change to support this. Is this good to merge now?

@keithpine Yes. This is good to merge.

**Review by osowski — APPROVED** [review]
This looks good to me. 

@shailesh-vaidya  Can you confirm which Jenkins jobs we should be running these changes against? I can deploy this branch locally without issue, but all the Jenkins jobs I tried failed - so there's a disconnect somewhere. I don't want to be using something you don't want us using or haven't updated.

**Pull request merged**
